name: release

on:
  push:
    tags:
      - '*'

jobs:
  syndicate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Task
      run: |
        curl -sL https://taskfile.dev/install.sh | sh
        sudo mv ./bin/task /usr/local/bin
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
    - name: Sync with GoDocs using Taskfile
      run: task godocs
      env:
        GIT_DOMAIN: ${{ github.server_url }}
        REPO: ${{ github.repository }}
        VERSION_SHORT: ${{ github.ref }}
